# Generated by Django 5.2.3 on 2026-02-19 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='商品标题')),
                ('description', models.TextField(verbose_name='商品描述')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods/', verbose_name='商品图片')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='商品价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上架时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否上架')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '商品',
                'db_table': 'goods',
            },
        ),
    ]
