# Generated by Django 5.2.3 on 2026-02-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_category_options_alter_goods_options'),
        ('orders', '0002_orders_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.goods', verbose_name='下单商品'),
        ),
    ]
